"""create user and profile_picture table migrations

Revision ID: 197ac14313d9
Revises: 
Create Date: 2023-11-08 15:55:53.664316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197ac14313d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user2_user_id', table_name='user2')
    op.drop_table('user2')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.create_table('user2',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='user2_pkey'),
    sa.UniqueConstraint('mail', name='user2_mail_key')
    )
    op.create_index('ix_user2_user_id', 'user2', ['user_id'], unique=False)
    # ### end Alembic commands ###
